-- 初始化脚本 - 下拉框数据
DELETE FROM T_SYS_COMBO_DATA WHERE BUSINESS_KEY IN ('BUS_COMPANY', 'BUS_CATEGORY');
INSERT INTO T_SYS_COMBO_DATA VALUES (UPPER(UUID()), 'BUS_COMPANY', 'SELECT CODE AS KEY, NAME AS VALUE FROM T_SYS_DICT', 'WHERE CATEGORY_KEY=''BUS_COMPANY''', 'ORDER BY SORT_NUMBER ASC', 'N', '390bbd49-087b-4ae7-a869-73d6b06445d2', CURRENT_TIMESTAMP);
INSERT INTO T_SYS_COMBO_DATA VALUES (UPPER(UUID()), 'BUS_CATEGORY', 'SELECT CODE AS KEY, NAME AS VALUE FROM T_SYS_DICT', 'WHERE CATEGORY_KEY=''BUS_CATEGORY''', 'ORDER BY SORT_NUMBER ASC', 'N', '390bbd49-087b-4ae7-a869-73d6b06445d2', CURRENT_TIMESTAMP);

INSERT INTO T_SYS_COMBO_DATA VALUES (UPPER(UUID()), 'STATION', 'SELECT ID AS KEY, NAME AS VALUE FROM T_BUS_STATION', 'WHERE DELETED = ''F''', 'ORDER BY NAME ASC', 'N', '390bbd49-087b-4ae7-a869-73d6b06445d2', CURRENT_TIMESTAMP);
